### PR TITLE
Automation Scripts

### PR DESCRIPTION
**Pull request by VideoGames1000**
Pulled all the relevant scripts from Community Framework and merged into processors. Prevents the potential for quickbar horseshit for people who just want some machinery.
_Probably_ won't conflict with Community Framework but I haven't tested it.

### CODE REVIEW

**Comment by Emmaker** [comment]
A fair request for a mod that has reached EOL. I'm going to be unlisting it anyways, might as well give those who still use it the ability to play without needing my newer mods.

**Comment by VideoGames1000** [comment]
Honestly I'd recommend splitting the automation scripts out of CF in general, since it seems like that mod's mostly meant as a menu and quickbar mod?

Keeping Processors around and repurposing it as your automation base makes more sense to me.

**Comment by Emmaker** [comment]
I'm going to be using my power scripts and such in Cosmic Expanse, my new big mod. It makes more sense for me to keep them in one unified framework to reduce the number of dependencies for CE.

**Comment by VideoGames1000** [comment]
I see where you're coming from, but I have to disagree.
There's a variety of reasons I find mixed-purpose mods (for reasons of not making dependencies or otherwise) bad practice, but I think the most relevant part is Community Framework's ongoing Quickbar issues.

I say it with full respect that the lexicon and quickbar features really would be _vastly_ better served as their own dedicated UI-tweaking mod, and letting CF be a dedicated _library_ as marketed. Having a few more dependencies is infinitely worth the simplification and stability you stand to gain by splitting the two off.

**Pull request merged**
